# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  azureContainerRegistry: registry20190813033530
  azureSubscriptionEndpoint: Azure subscription 1

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerCompose@0
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: 'Azure subscription 1(4e8499cd-4e5b-4067-9614-57fc34c7dad0)'
        azureContainerRegistry: '{"loginServer":"registry20190813033530.azurecr.io", "id" : "/subscriptions/4e8499cd-4e5b-4067-9614-57fc34c7dad0/resourceGroups/EshpResourceGroup/providers/Microsoft.ContainerRegistry/registries/registry20190813033530"}'
        dockerComposeFile: '**/docker-compose.yml'
        action: 'Run a Docker Compose command'
        dockerComposeCommand: build

